# Generated by Django 2.0 on 2020-06-03 16:05

import backend.endpoints.authenticate_endpoint
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('backend', '0002_useruserauthdjango'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsync',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', backend.service.auth_user_service.UserManagerAsync()),
            ],
        ),
        migrations.RenameField(
            model_name='useruserauthdjango',
            old_name='id',
            new_name='user_id',
        ),
    ]
