# Generated by Django 2.0 on 2020-06-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200603_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruserauthdjango',
            name='auth_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.UserAsync'),
        ),
    ]
