# Generated by Django 2.0 on 2020-06-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200603_1609'),
    ]
    atomic = False
    operations = [
        migrations.AlterModelTable(
            name='user',
            table='app_user',
        ),
    ]
