# # Generated by Django 2.0 on 2020-06-08 18:07

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200608_1616'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='AppUser',
        #     fields=[
        #         ('id', models.IntegerField(primary_key=True, serialize=False)),
        #         ('pseudo', models.CharField(max_length=100)),
        #         ('longitude', models.DecimalField(decimal_places=2, max_digits=4)),
        #         ('date_of_birth', models.DateField()),
        #         ('latitude', models.DecimalField(decimal_places=2, max_digits=4)),
        #         ('gender', models.CharField(max_length=20)),
        #     ],
        #     options={
        #         'db_table': 'app_user',
        #         'managed': settings.TESTING,
        #     },
        # ),
        # migrations.AlterField(
        #     model_name='useruserauthdjango',
        #     name='user_id',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.AppUser'),
        # ),
    ]
