# Generated by Django 2.2.13 on 2020-06-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200608_1807'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='User',
        # ),
    ]
